import { AssetType } from './asset-type.entity';

export const assetTypesSeed: Partial<AssetType>[] = [
  {
    assetGroup: 'STOCK',
    groupName: 'Ações',
    category: 'StockExchange',
    categoryName: 'Bolsa de Valores (BR e EUA)',
    assetGroupIRRF: 'STOCK',
    exemption: true,
    feePercent: 0.15,
    exemptionValue: 20000,
  },
  {
    assetGroup: 'STOCK_USA',
    groupName: 'Ações EUA',
    category: 'StockExchange',
    categoryName: 'Bolsa de Valores (BR e EUA)',
    assetGroupIRRF: 'STOCK_USA',
    exemption: true,
    feePercent: 0.15,
    exemptionValue: 35000,
  },
  {
    assetGroup: 'BDR',
    groupName: 'BDR',
    category: 'StockExchange',
    categoryName: 'Bolsa de Valores (BR e EUA)',
    assetGroupIRRF: 'STOCK',
    exemption: true,
    feePercent: 0.15,
    exemptionValue: 20000,
  },
  {
    assetGroup: 'EXPENSES',
    groupName: 'Despesas',
    category: 'StockExchange',
    categoryName: 'Bolsa de Valores (BR e EUA)',
    assetGroupIRRF: 'EXPENSES',
    exemption: false,
    feePercent: 0,
    exemptionValue: 0,
  },
  {
    assetGroup: 'RIGHT',
    groupName: 'Direito de subscrição',
    category: 'StockExchange',
    categoryName: 'Bolsa de Valores (BR e EUA)',
    assetGroupIRRF: 'STOCK',
    exemption: true,
    feePercent: 0.15,
    exemptionValue: 20000,
  },
  {
    assetGroup: 'FUTUSD',
    groupName: 'Dólar Futuro',
    category: 'StockExchange',
    categoryName: 'Bolsa de Valores (BR e EUA)',
    assetGroupIRRF: 'FUTUSD',
    exemption: false,
    feePercent: 0.15,
    exemptionValue: 0,
  },
  {
    assetGroup: 'ETF',
    groupName: 'ETF',
    category: 'StockExchange',
    categoryName: 'Bolsa de Valores (BR e EUA)',
    assetGroupIRRF: 'STOCK',
    exemption: false,
    feePercent: 0.15,
    exemptionValue: 0,
  },
  {
    assetGroup: 'ETF_FIXEDINCOME',
    groupName: 'ETF Renda Fixa',
    category: 'StockExchange',
    categoryName: 'Bolsa de Valores (BR e EUA)',
    assetGroupIRRF: 'ETF_FIXEDINCOME',
    exemption: true,
    feePercent: 0,
    exemptionValue: 0,
  },
  {
    assetGroup: 'ETF_USA',
    groupName: 'ETF USA',
    category: 'StockExchange',
    categoryName: 'Bolsa de Valores (BR e EUA)',
    assetGroupIRRF: 'ETF_USA',
    exemption: true,
    feePercent: 0.15,
    exemptionValue: 35000,
  },
  {
    assetGroup: 'FIAGRO',
    groupName: 'FI Agro',
    category: 'StockExchange',
    categoryName: 'Bolsa de Valores (BR e EUA)',
    assetGroupIRRF: 'FIAGRO',
    exemption: false,
    feePercent: 0.2,
    exemptionValue: 0,
  },
  {
    assetGroup: 'FII',
    groupName: 'Fundo Imobiliário',
    category: 'StockExchange',
    categoryName: 'Bolsa de Valores (BR e EUA)',
    assetGroupIRRF: 'FII',
    exemption: false,
    feePercent: 0.2,
    exemptionValue: 0,
  },
  {
    assetGroup: 'FUNDEXEMPTION',
    groupName: 'Fundos Isentos',
    category: 'StockExchange',
    categoryName: 'Bolsa de Valores (BR e EUA)',
    assetGroupIRRF: 'FUNDEXEMPTION',
    exemption: true,
    feePercent: 0,
    exemptionValue: 0,
  },
  {
    assetGroup: 'FUTOTH',
    groupName: 'Futuros Outros',
    category: 'StockExchange',
    categoryName: 'Bolsa de Valores (BR e EUA)',
    assetGroupIRRF: 'FUTOTH',
    exemption: false,
    feePercent: 0.15,
    exemptionValue: 0,
  },
  {
    assetGroup: 'FUTIDX',
    groupName: 'Índice Futuro',
    category: 'StockExchange',
    categoryName: 'Bolsa de Valores (BR e EUA)',
    assetGroupIRRF: 'FUTIDX',
    exemption: false,
    feePercent: 0.15,
    exemptionValue: 0,
  },
  {
    assetGroup: 'FUTFEE',
    groupName: 'Juros Futuros',
    category: 'StockExchange',
    categoryName: 'Bolsa de Valores (BR e EUA)',
    assetGroupIRRF: 'FUTFEE',
    exemption: false,
    feePercent: 0.15,
    exemptionValue: 0,
  },
  {
    assetGroup: 'FUNDS_USA',
    groupName: 'Mutual Funds USA',
    category: 'StockExchange',
    categoryName: 'Bolsa de Valores (BR e EUA)',
    assetGroupIRRF: 'FUNDS_USA',
    exemption: false,
    feePercent: 0,
    exemptionValue: 0,
  },
  {
    assetGroup: 'OPTION',
    groupName: 'Opções',
    category: 'StockExchange',
    categoryName: 'Bolsa de Valores (BR e EUA)',
    assetGroupIRRF: 'OPTION',
    exemption: false,
    feePercent: 0.15,
    exemptionValue: 0,
  },
  {
    assetGroup: 'OPTION_USA',
    groupName: 'Opções EUA',
    category: 'StockExchange',
    categoryName: 'Bolsa de Valores (BR e EUA)',
    assetGroupIRRF: 'OPTION_USA',
    exemption: true,
    feePercent: 0,
    exemptionValue: 0,
  },
  {
    assetGroup: 'FLEXOPTION',
    groupName: 'Opções Flexíveis',
    category: 'StockExchange',
    categoryName: 'Bolsa de Valores (BR e EUA)',
    assetGroupIRRF: 'FLEXOPTION',
    exemption: false,
    feePercent: 0,
    exemptionValue: 0,
  },
  {
    assetGroup: 'GOLD',
    groupName: 'Ouro na bolsa',
    category: 'StockExchange',
    categoryName: 'Bolsa de Valores (BR e EUA)',
    assetGroupIRRF: 'STOCK',
    exemption: true,
    feePercent: 0.15,
    exemptionValue: 20000,
  },
  {
    assetGroup: 'REIT',
    groupName: 'REIT',
    category: 'StockExchange',
    categoryName: 'Bolsa de Valores (BR e EUA)',
    assetGroupIRRF: 'REIT',
    exemption: true,
    feePercent: 0,
    exemptionValue: 0,
  },
  {
    assetGroup: 'FIXED_INCOME_USA',
    groupName: 'Renda Fixa EUA',
    category: 'StockExchange',
    categoryName: 'Renda Fixa EUA',
    assetGroupIRRF: 'FIXED_INCOME_USA',
    exemption: false,
    feePercent: 0,
    exemptionValue: 0,
  },
  {
    assetGroup: 'TERM',
    groupName: 'Termo',
    category: 'StockExchange',
    categoryName: 'Bolsa de Valores (BR e EUA)',
    assetGroupIRRF: 'TERM',
    exemption: false,
    feePercent: 0,
    exemptionValue: 0,
  },
];
